# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and Push Docker Images
      run: |
           docker build . --file ./deploy1/Dockerfile -t deploy1:latest
           docker build . --file ./deploy2/Dockerfile -t deploy2:latest
           docker build . --file ./deploy3/Dockerfile -t deploy3:latest
       
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: deploy1/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy1:latest
    - name: Build and push
      id: docker_build2
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: deploy2/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy2:latest
    - name: Build and push
      id: docker_build3
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: deploy3/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy3:latest
